### ISSUE TITLE
任务中心

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/dashboard#10]
## 侧边栏新增 任务中心
![image](https://user-images.githubusercontent.com/8476969/159147878-0a480867-8b47-4c1c-8899-f07a48c6cbb3.png)

- [x] 已完成

**Comment by iRuxu** [comment]
## 任务中心

![image](https://user-images.githubusercontent.com/8476969/159147957-ddd6e6ae-ad32-408b-9ce4-58637cbd1fee.png)

**Comment by iRuxu** [comment]
接口见：https://github.com/JX3BOX/jx3box-pay/issues/64

**Comment by iRuxu** [comment]
https://github.com/JX3BOX/jx3box-pay/issues/64

使用第一个接口渲染列表。
http://pay.jx3box.com/api/personal/task?is_limit_everyday=0

当hasFinished=true时，按钮禁用，显示为“已完成"
当hasFinished=false时，按钮启用，显示为"完成任务"

点击完成时，请求第2个接口
https://pay.jx3box.com/api/personal/task/18/check-status

**Comment by iRuxu** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/8476969/167682202-464482eb-d33d-4ece-a310-75a04441e1af.png">

action_type_desc 是任务名称
task_url 是任务链接（就是任务名称的链接）
task_detail 是任务的长描述

**Comment by zixuan1986** [comment]
![image](https://user-images.githubusercontent.com/40552272/167782576-7610a046-045e-4770-bc2e-4950b79e9021.png)
m没有返回task_detail 字段，现在显示可获取的经验或积分
