### ISSUE TITLE
推广中心

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/dashboard#79]
## UI

参考我的盒币

<img width="1625" alt="image" src="https://github.com/user-attachments/assets/bb83e7d4-f849-472b-93ed-6eedabf70337">

- [x] 已完成

**Comment by iRuxu** [comment]
## 公告调用

`key`：user_invitation_register

接口：醉栩补充到这里告诉新人

- [ ] 已完成

**Comment by iRuxu** [comment]
## 接口

对应接口醉栩补充到这里告诉新人

- [ ] 已完成

**Comment by iRuxu** [comment]
## 任务中心

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/2f85cf8b-c4a5-42b0-8e90-5df802c8e8ed">

接口：小胡补充在这里

- [ ] 已完成

**Comment by flyflyknife** [comment]
https://github.com/JX3BOX/jx3box-cms/issues/35

**Comment by flyflyknife** [comment]
管理个人相关接口见：

https://swagger.jx3box.com/swagger.html?urls.primaryName=pay.jx3box.com#/%E7%AE%A1%E7%90%86%E7%94%A8%E6%88%B7%E4%BB%BB%E5%8A%A1%E4%B8%AD%E5%BF%83

**Comment by flyflyknife** [comment]
用户个人相关接口见：

https://swagger.jx3box.com/swagger.html?urls.primaryName=pay.jx3box.com#/%E7%94%A8%E6%88%B7%E4%BB%BB%E5%8A%A1%E4%B8%AD%E5%BF%83

**Comment by flyflyknife** [comment]
目前 已经推广任务添加到了 数据库，可以从接口 https://pay.jx3box.com/api/personal/task 看到，需要根据上述管理接口 修改任务图标以及 连接地址，或直接修改数据库 jx3box_vip.point_experience_action_type_setting 表的相关字段内容

**Comment by flyflyknife** [comment]
-------------
问题：
发放经验和积分可以由会员中心处理，邀请人员的勋章和称号 也可以有会员中心处理，但是被邀请人的勋章 应该是注册阶段发放？


如果放在领取奖励阶段发放， 那么要循环遍历 邀请人所有的邀请历史数据 找到 对应被邀请人 来发放勋章记录，这个处理逻辑不太合理。 因为邀请到10个以后，其实就不能领取奖励了，那么他邀请到第11个由于没法触发领取奖励

**Comment by iRuxu** [comment]
> 问题： 发放经验和积分可以由会员中心处理，邀请人员的勋章和称号 也可以有会员中心处理，但是被邀请人的勋章 应该是注册阶段发放？
> 
> 如果放在领取奖励阶段发放， 那么要循环遍历 邀请人所有的邀请历史数据 找到 对应被邀请人 来发放勋章记录，这个处理逻辑不太合理。 因为邀请到10个以后，其实就不能领取奖励了，那么他邀请到第11个由于没法触发领取奖励

数据库始终只做记录，在任务中心，他们需要自己去点击“完成”任务，你的完成接口，查询历史记录，满足条件时，发放对应的奖励。
注册部分就是查这个邀请码的使用记录

- [ ] 已完成

**Comment by iRuxu** [comment]
## 复制

<img width="1603" alt="image" src="https://github.com/user-attachments/assets/ea296766-7d5b-4f4c-9c84-bcc813097f24">

- [ ] 已完成
