### ISSUE TITLE
反馈协同

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/dashboard#93]
<img width="1473" alt="image" src="https://github.com/user-attachments/assets/4f2f76ea-2ed1-4e8b-99b4-5ac60debe900">

在处理中状态时，增加一个按钮，叫协同。

点击弹一个对话框。

像指派一样，可以选其他人（多选）。
另外可以设置备注（写入日志）

微信公众号和短消息需要通知多个协同人。

---
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/95b84a41-eb09-4cd2-9744-944cfdee7403">
<img width="908" alt="image" src="https://github.com/user-attachments/assets/164b8c5f-14cd-4ca2-802d-e0f91d60b532">

- [x] 后端：已完成
- [x] 前端：已完成

**Comment by Kaviilee** [comment]
## 模板使用错误
![image](https://github.com/user-attachments/assets/e4e23696-5f09-4ed1-ba85-d254ccea8a35)

模板的id应该是 mIo9_bWccVXcmo_VNgL5M7E2zGTDxofywKOk27g5Lek

**Comment by flyflyknife** [comment]
https://swagger.jx3box.com/swagger.html?urls.primaryName=next2.jx3box.com#/%E5%8F%8D%E9%A6%88/Miscfeedback_Coordination

**Comment by iRuxu** [comment]
<img width="981" alt="image" src="https://github.com/user-attachments/assets/f9817777-005b-4391-b559-5b81496795b5">

- [ ] 已完成
